name: Heroku Build + Deploy

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Heroku container registry login
        run: docker login -u _ -p $HEROKU_API_KEY registry.heroku.com

      - name: Build Image
        run: |
          cd ./app
          docker pull $HEROKU_REGISTRY_IMAGE || true
          docker build . --cache-from $HEROKU_REGISTRY_IMAGE --tag $HEROKU_REGISTRY_IMAGE --file ./Dockerfile

      - name: Push Image
        run: |
          docker push $HEROKU_REGISTRY_IMAGE

      - name: Heroku Deploy
        run: |
          cd ./app
          chmod +x ./heroku_release.sh
          ./heroku_release.sh