name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fierce-retreat-10367"
          heroku_email: "endakelly@emk-solutions.net"
          usedocker: true
          appdir: app 
          docker_build_args: |
            NODE_ENV
            SECRET_KEY
            PORT
        env:
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          PORT: ${{ secrets.DJANGO_APP_PORT }}